Specify webpack version to 3.11.0
For webpack v4.5.0,  install webpack-cli error,such as:【so set the webpack to specific version of 3.11.0】
D:\parity\mydapp>webpack
The CLI moved into a separate package: webpack-cli
Would you like to install webpack-cli? (That will run npm install -D webpack-cli) (yes/NO)yes
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN semantic-ui-react@0.68.5 requires a peer of react@>=0.14.0 <= 15 but none is installed. You must install peer dependencies yourself.
npm WARN semantic-ui-react@0.68.5 requires a peer of react-dom@>=0.14.0 <= 15 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ webpack-cli@2.0.14
added 279 packages and removed 1 package in 20.745s
{ Error: Cannot find module 'webpack-cli'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at runCommand.then.result (C:\Users\k\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js:62:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'MODULE_NOT_FOUND' }